name: periodic-broken-link-checks

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/check-links.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://openziti.github.io/
          cmd_params: >
            --color=always 
            --exclude=https://(EXWPKK5PV4-dsn.algolia.net|www.googletagmanager.com|mermaid-js.github.io|mermaid.live|github.com/openziti/ziti-doc/blob/main/docusaurus/|play.google.com/store/apps/details\?id=io\.netfoundry\.ziti\.tunnel|apps.apple.com/app/|github.com/openziti/ziti-doc/tree/main/docusaurus/)|#docusaurus_skipToContent_fallback$
            --buffer-size=8192 
            --max-connections=10
            --rate-limit=10
            --header=User-Agent:curl/7.54.0
            --timeout=20
          debug: true
