name: periodic-broken-link-checks

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/check-links.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v3
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://openziti.github.io/
          cmd_params: >
            --color=always 
            --exclude=https://(EXWPKK5PV4-dsn.algolia.net|www.google.com/search|www.googletagmanager.com|mermaid-js.github.io|mermaid.live|play.google.com/|apps.apple.com/|www.reddit.com/r/openziti|github.com/.*/releases/latest/download/)|(#docusaurus_skipToContent_fallback|\.(ziti|svc)(/[^.]+)?)$
            --buffer-size=8192 
            --max-connections-per-host=5
            --header=User-Agent:curl/7.54.0
            --timeout=20
          debug: false
      - name: Resolve Alarm Issue if Links are Not Broken
        if: ${{ success() }}
        uses: DavidMarquezF/close-matching-issues@v3.0.1
        with:
          query: 'is:open label:bug in:title "Broken Links Alarm"'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Raise an Alarm Issue if Links are Broken
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.1
        with:
          update_existing: true
          search_existing: open
          filename: ./check-links/check-links-issue-template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  popular-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v3
      - name: Check popular links to new docs site
        run: ./check-links.sh https://docs.openziti.io ./popular-docs-links.txt
        working-directory: ./check-links/
      - name: Check popular links to old docs site
        run: ./check-links.sh https://openziti.github.io ./popular-docs-links.txt
        working-directory: ./check-links/
      - name: Resolve Alarm Issue if Links are Not Broken
        if: ${{ success() }}
        uses: DavidMarquezF/close-matching-issues@v3.0.1
        with:
          query: 'is:open label:bug in:title "Popular Links Alarm"'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Raise an Alarm Issue if Links are Broken
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.1
        with:
          update_existing: true
          search_existing: open
          filename: ./check-links/popular-links-issue-template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
