name: periodic-broken-link-checks

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/check-links.yml

jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v3
      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://openziti.github.io/
          cmd_params: >
            --color=always 
            --exclude=https://(EXWPKK5PV4-dsn.algolia.net|www.googletagmanager.com|mermaid-js.github.io|mermaid.live|github.com/openziti/ziti-doc/blob/main/docusaurus/|play.google.com/store/apps/details\?id=io\.netfoundry\.ziti\.tunnel|apps.apple.com/app/|github.com/openziti/ziti-doc/tree/main/docusaurus/)|#docusaurus_skipToContent_fallback$
            --buffer-size=8192 
            --max-connections-per-host=5
            --header=User-Agent:curl/7.54.0
            --timeout=20
          debug: true
      - name: Resolve Alarm Issue if Links are Not Broken
        if: ${{ success() }}
        uses: DavidMarquezF/close-matching-issues@v3.0.1
        with:
          query: 'is:open label:bug in:title "Broken Links Alarm"'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Raise an Alarm Issue if Links are Broken
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.1
        with:
          update_existing: true
          search_existing: open
          filename: .github/workflows/check-links-issue-template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
