name: build and deploy docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC to keep companion microsites updated e.g. swift SDK docs

jobs:
  publish-docs-from-container:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: main
      gh_ci_key: ${{ secrets.GH_CI_KEY }}
      ziti_ci_gpg_key: ${{ secrets.ZITI_CI_GPG_KEY }}
      ziti_ci_gpg_key_id: ${{ secrets.ZITI_CI_GPG_KEY_ID }}
    steps:
      - name: Checkout Workspace
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update \
          && sudo apt-get install -y doxygen

      - name: Build & Publish Docusaurus Site
        run: ./publish.sh

  check-links:
    needs: publish-docs-from-container
    name: Check for Broken Links
    uses: ./.github/workflows/check-links.yml
    secrets: inherit
